# Generated by Django 2.0.2 on 2018-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeload', '0002_auto_20180306_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='title',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
