# Generated by Django 2.0.2 on 2018-03-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeload', '0003_solutions_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='title',
        ),
    ]
