# Generated by Django 2.0.2 on 2018-03-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeload', '0006_auto_20180307_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='source',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_file',
            field=models.FileField(null=True, upload_to='solution_tests/'),
        ),
    ]
