# Generated by Django 2.0.2 on 2018-03-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeload', '0009_auto_20180314_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='solved_string',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
