# Generated by Django 2.0.2 on 2018-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeload', '0010_auto_20180314_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
